apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/nginx_status"
        prometheus.io/port: "8080"
        prometheus.io/insecure: "true"  # This is not always supported, check your version.

    spec:
      containers:
      - name: nginx
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/nginx-bop:83-83
        ports:
        - containerPort: 80   # Port for HTTP
        - containerPort: 443  # Port for HTTPS
        - containerPort: 8080
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Ensure no pod is unavailable during the update
      maxSurge: 1  # Allow 1 additional pod above the desired replica count during the update
