apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage
spec:
  replicas: 1  # Keep 1 replica for rolling update with minimal downtime
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: statuspage
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-bop:83-83
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Ensure no pod is unavailable during the update
      maxSurge: 1  # Allow 1 additional pod above the desired replica count during the update
